# -*- coding: utf-8 -*-
"""Info: Seq retrieval from Biological DB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-2lkrYbytanb3mF4eg2-O_iJK9x5lrq
"""

!pip install Bio

import os
from google.colab import files
from Bio import SeqIO, Entrez
mysearch = Entrez.esearch(db='nucleotide',term="alzheimer's AND biomol_mRNA[PROP]", retmax = 5) #biomol_mRNA tells ncbi you only want mRNA results of query
myrecord = Entrez.read(mysearch)
mysearch.close()
myids=myrecord["IdList"]
for id1 in myids:
  Entrez.email='kanvaudupa.bt23@rvce.edu.in' #always tell NCBI (server for genbank db) who you are
  net_handle = Entrez.efetch(
      db='nucleotide', id=id1, rettype="fasta", retmode="text"   #Retrieve data for each id
    )
  record = SeqIO.read(net_handle, "fasta")
  net_handle.close()
  record.seq= record.seq.transcribe()             #Transcribe the default cDNA format to mRNA (T->U)
  filename = id1 + "_RNA.fasta"
  SeqIO.write(record, filename, "fasta")          #Save transcript

  files.download(filename)
  myrecord = SeqIO.read(filename,"fasta")
  print(myrecord.format('fasta'))                 #Display in full via the formatting